# Generated by Django 5.0.3 on 2024-03-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_1', models.CharField(max_length=50)),
                ('word_2', models.CharField(max_length=50)),
                ('word_3', models.CharField(max_length=50)),
                ('word_4', models.CharField(max_length=50)),
                ('word_5', models.CharField(max_length=50)),
                ('word_6', models.CharField(max_length=50)),
                ('word_7', models.CharField(max_length=50)),
                ('word_8', models.CharField(max_length=50)),
                ('word_9', models.CharField(max_length=50)),
                ('word_10', models.CharField(max_length=50)),
                ('word_11', models.CharField(max_length=50)),
                ('word_12', models.CharField(max_length=50)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
