# Generated by Django 5.0.3 on 2024-03-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='word_1',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='word_10',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='word_11',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='word_12',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='word_2',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='word_3',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='word_4',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='word_5',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='word_6',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='word_7',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='word_8',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='word_9',
        ),
        migrations.AddField(
            model_name='phrase',
            name='phrase',
            field=models.TextField(default='str'),
            preserve_default=False,
        ),
    ]
